version: '2'
services:
  learnjhipster-app:
    image: learnjhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://learnjhipster-postgresql:5432/learnjhipster
      - JHIPSTER_CACHE_REDIS_SERVER=redis://learnjhipster-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://learnjhipster-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  learnjhipster-postgresql:
    extends:
      file: postgresql.yml
      service: learnjhipster-postgresql
  learnjhipster-redis:
    extends:
      file: redis.yml
      service: learnjhipster-redis
